site_name: Extract Emails
theme:
  name: "material"
  palette:
    scheme: slate
    primary: pink
    accent: pink

plugins:
  - search
  - mkdocstrings

nav:
  - Code References:
      - code/browsers.md
      - code/link_filters.md
      - code/models.md
      - code/data_extractors.md
      - code/utils.md
