[tool.poetry]
name = "extract-emails"
version = "5.0.0"
description = "Extract email addresses from given URL."
authors = ["Dmitrii Kurlov <dmitriik@tutanota.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
