[tool.poetry]
name = "extract-emails"
version = "5.0.0"
description = "Extract email addresses from given URL."
authors = ["Dmitrii Kurlov <dmitriik@tutanota.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.9"
requests = "^2.26.0"
selenium = "^3.141.0"
httpx = "^0.19.0"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest_async = "^0.1.1"
tox = "^3.24.3"
mkdocs-material = "^7.2.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
